### ISSUE TITLE
Cannot build PDF

### ISSUE THREAD

**Issue by wesbos** [GitbookIO/gitbook#1056]
I think this is an issue with Calibre, but I was hoping you might have some insight into this error:

Reason: Incompatible library version: QtWidgets.so requires version 5.4.0 or later, but QtWidgets provides version 5.3.0

I've tried downgrading to Calibre 2.44.1 from 2.45, but no luck. Any ideas? Here is the entire error after running `gitbook pdf` 

```
info: loading book configuration....OK
info: load plugin gitbook-plugin-atoc ....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-search ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: >> 5 plugins loaded
info: start generation with pdf generator
info: clean pdf generatorOK
info: write SUMMARY.html
info: start conversion to pdf ....ERROR

Error: Command failed: /bin/sh -c ebook-convert /var/folders/59/g589lhvn3_n31qg4f1h6gv240000gn/T/tmp-7986k03bba8/SUMMARY.html /var/folders/59/g589lhvn3_n31qg4f1h6gv240000gn/T/tmp-7986k03bba8/index.pdf --title="Introduction" --comments="" --language="en" --book-producer="GitBook" --publisher="GitBook" --chapter="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter ')]" --level1-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-1 ')]" --level2-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-2 ')]" --level3-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-3 ')]" --no-chapters-in-toc --max-levels="1" --breadth-first --chapter-mark="pagebreak" --page-breaks-before="/" --margin-left="62" --margin-right="62" --margin-top="56" --margin-bottom="56" --pdf-default-font-size="12" --pdf-mono-font-size="12" --paper-size="a4" --pdf-header-template="<html>
    <body style=\"font-family: sans-serif; color: #000; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">
        <div class=\"pdf-header\" style=\"margin-top: 20px; color: #aaa; padding-bottom: 10px; border-bottom: 1px solid #eee;\">
            <span>_TITLE_</span>
        </div>
    </body>
</html>" --pdf-footer-template="<html>
    <body style=\"font-family: sans-serif; color: #000; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">
        <div class=\"pdf-footer\" style=\"margin-top: 20px; color: #aaa; padding-top: 10px; border-top: 1px solid #eee;\">
            <span>_SECTION_</span>
            <span class=\"footer-pages-count\" style=\"float: right;\">_PAGENUM_</span>
        </div>
    </body>
</html>" --pdf-sans-family="Arial"
Python function terminated unexpectedly: dlopen(/Applications/calibre.app/Contents/Resources/Python/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/calibre.app/Contents/Resources/Python/site-packages/PyQt5/QtWidgets.so
  Reason: Incompatible library version: QtWidgets.so requires version 5.4.0 or later, but QtWidgets provides version 5.3.0
Traceback (most recent call last):
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 209, in main
    return run_entry_point()
  File "/Applications/calibre.app/Contents/Resources/Python/lib/python2.7/site.py", line 114, in run_entry_point
    return getattr(pmod, func)()
  File "site-packages/calibre/ebooks/conversion/cli.py", line 360, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1207, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 122, in convert
  File "site-packages/calibre/gui2/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/calibre.app/Contents/Resources/Python/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: @executable_path/../Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/calibre.app/Contents/Resources/Python/site-packages/PyQt5/QtWidgets.so
  Reason: Incompatible library version: QtWidgets.so requires version 5.4.0 or later, but QtWidgets provides version 5.3.0
 1% Converting input to HTML...
InputFormatPlugin: HTML Input running
on /var/folders/59/g589lhvn3_n31qg4f1h6gv240000gn/T/tmp-7986k03bba8/SUMMARY.html
Creator not specified
Building file list...
Normalizing filename cases
Rewriting HTML links
34% Running transforms on ebook...
Merging user specified metadata...
Detecting structure...
	Detected chapter: Introduction
	Detected chapter: Introduction.md
	Detected chapter: Getting Started.md
	Detected chapter: The Command Palette.md
	Detected chapter: Editor Settings & Customization.md
	Detected chapter: Code Completion and Intelligence.md
	Detected chapter: Terminal and Command Line Integration.md
	Detected chapter: Maximizing screen real estate with multiple panes
	Detected chapter: Working with multiple carets.md
	Detected chapter: Themes and Colour Schemes.md
	Detected chapter: Snippets.md
	Detected chapter: Efficient Searching, Finding and Replacing.md
	Detected chapter: Moving Selecting, Expanding and Wrapping.md
	Detected chapter: Code Folding.md
	Detected chapter: Projects.md
	Detected chapter: Master Keyboard Shortcuts.md
	Detected chapter: Recording and Playing Macros.md
	Detected chapter: Running, Testing and Deploying with Build Systems.
	Detected chapter: Bookmarks.md
	Detected chapter: Working with Git.md
	Detected chapter: Mastering HTML + CSS with Emmet.md
	Detected chapter: Workflow and Code Quality Tooling.md
	Detected chapter: Adding a dash of Vim.md
	Detected chapter: Language Specific Tweaks.md
	Detected chapter: Must have add-on Packages.md
	Detected chapter: Tips + Tricks Grab Bag.md
	Detected chapter: fin.md
Auto generated TOC with 27 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
```

It happens with every install, even an empty repo with nothing but a title.

**Comment by SamyPesse** [comment]
We are still using version `2.41.0` on GitBook.com; can you test with this version?

Why are you not using GitBook.com?

**Comment by wesbos** [comment]
Yes - I'll try that out. 

I just want to test out GitBook before I commit to it and pay for it and I can't test my private book on GitBook.com for free

**Comment by AaronO** [comment]
Hi @wesbos,

I just wanted to chip in here, calibre's `ebook-convert` can be a bit of a pain to setup, as you may have noticed. We use `calibre`@`2.41.0` in production (on `linux`).

A local install of `calibre` does work for me, so we would have to dig into the specifics of your setup to see why it doesn't work on your mac.

This is one of the reasons why we recommend using `gitbook.com`'s automated builds, it's dead simple to setup and most importantly reliable, it's also free for open/free projects.

Feel free to give it a try, and let us know if there's anything we can do to help !

**Comment by wesbos** [comment]
Thanks - going to give the paid plan a shot.
