### ISSUE TITLE
Error: Cannot find module 'config-chain'

### ISSUE THREAD

**Issue by saturngod** [GitbookIO/gitbook#1061]
After updating latest node.js version 5.2.0 and update gitbook version , cannot use the gitbook anymore. I always got the 

```
Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitbook-cli/node_modules/npm/lib/config/core.js:2:10)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
```

Is gitbook support the node.js version 5.2 or not yet ?

**Comment by saturngod** [comment]
After remove gitbook and install again , it work

```
$ npm remove gitbook-cli -g
$ npm install gitbook-cli -g
```
