### ISSUE TITLE
Gitbook update error

### ISSUE THREAD

**Issue by iamchathu** [GitbookIO/gitbook#1152]
I get error when i try to update gitbook

```
>gitbook versions:update
Installing GitBook 2.6.7
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EIO
    at exports._errnoException (util.js:870:11)
    at WriteStream.Socket._writeGeneric (net.js:675:26)
    at WriteStream.Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at WriteStream.Writable.write (_stream_writable.js:207:11)
    at WriteStream.Socket.write (net.js:618:40)
    at Console.log (console.js:36:16)
    at C:\Users\Chathu\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules
\npm\lib\install.js:137:27
    at C:\Users\Chathu\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules
\npm\lib\install.js:268:7

```

**Comment by iamchathu** [comment]
Got fixed by removing gitbook and gitbook cli and installing it again both.
