### ISSUE TITLE
fail to generate pdf file

### ISSUE THREAD

**Issue by knight42** [GitbookIO/gitbook#1257]
```
$ node -v
v6.0.0


$ gitbook -v 3.0.0-pre.9 -d pdf

info: 6 are installed 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: preparing the generation 
warn: "sections" property is deprecated, use page.content instead 
warn: "generator" property is deprecated, use "output.generator" instead 
warn: "book" property is deprecated, use "this" directly instead 
warn: "sections" property is deprecated, use page.content instead 
warn: "sections" property is deprecated, use page.content instead 
.
. (same warning)

Template render error: (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/gitbook-plugin-theme-default/_layouts/ebook/pdf_header.h
tml)
  ReferenceError: template is not defined
Template render error: (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/gitbook-plugin-theme-default/_layouts/ebook/pdf_header.h
tml)
  ReferenceError: template is not defined
    at Object.exports.prettifyError (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/lib.js:34:15)
    at /home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.js:485:31
    at root [as rootRenderFunc] (eval at <anonymous> (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.j
s:564:24), <anonymous>:43:3)
    at Obj.extend.render (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.js:478:15)
    at /home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.js:311:35
    at createTemplate (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.js:234:25)
    at handle (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.js:249:25)
    at /home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/environment.js:263:21
    at next (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/lib.js:207:13)
    at Object.exports.asyncIter (/home/knight/.gitbook/versions/3.0.0-pre.9/node_modules/nunjucks/src/lib.js:214:5)


```

**Comment by knight42** [comment]
In addition, command `gitbook pdf` with gitbook@2.6.7 will also fail in Node.js v6, since `path.extname` no longer accpets `undefined`.

To be more specific, [this line](https://github.com/GitbookIO/gitbook/blob/d8f5aa680dfa0bda27864598f2f93a6012143853/lib/index.js#L76) should be replaced by
`var output = args[1] || '';`

**Comment by SamyPesse** [comment]
It should be working with latest pre versions, can you test and let me know if that's not the case.

GitBook v3 is also supporting Node v6.

**Comment by knight42** [comment]
@SamyPesse No error, but the bookmark tree in the generated pdf got flatten.
