### ISSUE TITLE
pre.14 Template Error when generating PDF

### ISSUE THREAD

**Issue by cycomachead** [GitbookIO/gitbook#1299]
You can use this tag in my book to mess around...

https://github.com/cycomachead/thesis/tree/46018eac3038ceeeeb7b1934726194207f0c3cbb

It _appears_ that simply removing the `"style":{}` object from my book.json works causes things to work...which seems odd. If I remove it, my styles still seem to be picked up, so that's 👍, but this error is certainly odd.

Here's the `gitbook pdf` command, and it's output.
```
Michael at Yosemite-Pro in ~/Dropbox/Projects/thesis on master*
👉 gitbook pdf -v 3.0.0-pre.14 -d --log-level=debug && o book.pdf
info: 7 plugins are installed 
info: loading plugin "bibtex-citation-michael"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 20 pages 
info: found 193 asset files 
error: error while generating page "abstract.md": 

Template render error: (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/gitbook-plugin-theme-default/_layouts/ebook/page.html)
  TypeError: Cannot read property '0' of undefined
Template render error: (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/gitbook-plugin-theme-default/_layouts/ebook/page.html)
  TypeError: Cannot read property '0' of undefined
    at Object.exports.prettifyError (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/lib.js:34:15)
    at /Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:485:31
    at eval (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:49:11)
    at eval (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:88:12)
    at b_style (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:146:3)
    at Obj.extend.getSuper (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:393:9)
    at b_style (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:87:9)
    at eval (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:48:84)
    at b_description (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:76:1)
    at eval (eval at <anonymous> (/Volumes/Michael/Users/Michael/.gitbook/versions/3.0.0-pre.14/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:28:90)
```

**Comment by cycomachead** [comment]
P.S. Sorry @SamyPesse For the many comments in so few days (deadlines approaching...), but thank you very much for being incredibly responsive!

**Comment by SamyPesse** [comment]
@cycomachead No worries, thank you for the awesome feedback 👍 , it help us a lot!

I'll fix this bug and others today, then release a `3.0.0-pre.15`.

**Comment by SamyPesse** [comment]
@cycomachead I fixed the issue, but I have issues locally with the image captions plugin.
