### ISSUE TITLE
Validation of configuration for "readme": "book-intro.adoc" is failing

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#1316]
The validation of the configuration is failing for this book (https://github.com/jaceklaskowski/mastering-apache-spark-book), because the regex for structure file doesn't accept dot in filenames.

**Comment by nagim** [comment]
Hi,

With the 3.0.2 update, the regex for structure file no longer accepts uppercase characters, only lowercase:
```
ConfigurationError: Error with book's configuration: config.structure.readme does not match pattern "^[a-z-._d,s]+$"
ConfigurationError: Error with book's configuration: config.structure.readme does not match pattern "^[a-z-._d,s]+$"
    at createError (/root/.gitbook/versions/3.0.2/node_modules/error/typed.js:31:22)
    at new createError (/root/.gitbook/versions/3.0.2/node_modules/error/wrapped.js:88:19)
    at validateConfig (/root/.gitbook/versions/3.0.2/lib/parse/validateConfig.js:23:15)
    at /root/.gitbook/versions/3.0.2/lib/parse/parseConfig.js:41:18
From previous event:
    at Object.module.exports.exec (/root/.gitbook/versions/3.0.2/lib/cli/install.js:17:10)
    at Object.exec (/usr/local/lib/node_modules/gitbook-cli/lib/commands.js:35:16)
    at /usr/local/lib/node_modules/gitbook-cli/bin/gitbook.js:174:33
    at _fulfilled (/usr/local/lib/node_modules/gitbook-cli/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/gitbook-cli/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/gitbook-cli/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/gitbook-cli/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/gitbook-cli/node_modules/q/q.js:137:13)
```

**Comment by SamyPesse** [comment]
Thank @nagim I've fixed it gain.
