### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by MarcoHengstenberg** [GitbookIO/gitbook#135]
I have no idea what to make out of this error message.

I have installed Gitbook a few weeks ago and have recently started to create a book. Now, all out of a sudden, it refrains from doing the `gitbook serve` task by telling me "TypeError: Cannot read property 'text' of undefined".

I just did the `npm install gitbook -g` command again to get the current version of Gitbook. Now, when doing the `gitbook serve` task the following output is given:

Starting build ...
TypeError: Cannot read property 'text' of undefined
    at parseChapter (/usr/local/lib/node_modules/gitbook/lib/parse/summary.js:94:46)
    at Function.map (/usr/local/lib/node_modules/gitbook/node_modules/lodash/dist/lodash.js:3508:27)
    at lodash.ctor.(anonymous function) [as map](/usr/local/lib/node_modules/gitbook/node_modules/lodash/dist/lodash.js:5924:31)
    at Object.parseSummary [as summary](/usr/local/lib/node_modules/gitbook/lib/parse/summary.js:107:6)
    at /usr/local/lib/node_modules/gitbook/lib/generate/index.js:125:45
    at _fulfilled (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/gitbook/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:108:17)

**Comment by jicksta** [comment]
I ran into this as well. Was kinda surprised it was just a formatting issue. Some warning would be nice. This is an errors that many folks who are wanting to try gitbook will bump into literally on their first execution of the gitbook command. Thanks for the work on gitbook btw!

**Comment by oubiwann** [comment]
This one just bit me as well. Couldn't figure out why the new book wasn't building. This is my third gitbook, and I wanted to try a deeper content structure ...
