### ISSUE TITLE
Build fails at conrefs

### ISSUE THREAD

**Issue by nagim** [GitbookIO/gitbook#1374]
I've been building using the new builder (1.5.3) and v3.1.0 and it failed at conrefs, I think.

Error message:

```
Template render error: 
 TypeError: content.replace is not a function
Template render error: 
 TypeError: content.replace is not a function
   at Object.exports.prettifyError (/root/.gitbook/versions/3.1.0/node_modules/nunjucks/src/lib.js:34:15)
   at /root/.gitbook/versions/3.1.0/node_modules/nunjucks/src/environment.js:485:31
   at eval (eval at <anonymous> (/root/.gitbook/versions/3.1.0/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:10:11)
   at createTemplate (/root/.gitbook/versions/3.1.0/node_modules/nunjucks/src/environment.js:212:25)
   at handle (/root/.gitbook/versions/3.1.0/node_modules/nunjucks/src/environment.js:245:25)
   at _combinedTickCallback (internal/process/next_tick.js:67:7)
   at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
   at Object.renderTemplate [as render] (/root/.gitbook/versions/3.1.0/lib/templating/render.js:38:10)
   at /root/.gitbook/versions/3.1.0/lib/output/generatePage.js:49:35
```

**Comment by nagim** [comment]
Great, thanks! 👍
