### ISSUE TITLE
TypeError: Cannot set property 'name' of undefined

### ISSUE THREAD

**Issue by qiuggv** [GitbookIO/gitbook#1417]
while running command "gitbook build ./ --log=debug --debug"

```
debug: index page gong_gong_kai_fa_kuang_jia/hou_duan_kai_fa_kuang_jia/dai_ma_sheng_cheng_shi_yong_zhi_nan.md
error: error while generating page "gong_gong_kai_fa_kuang_jia/hou_duan_kai_fa_kuang_jia/dai_ma_sheng_cheng_shi_yong_zhi_nan.md":

TypeError: Cannot set property 'name' of undefined
TypeError: Cannot set property 'name' of undefined
    at Record.TemplateBlock.normalizeBlockResult (/home/qiuxy/.gitbook/versions/3.1.1/lib/models/templateBlock.js:223:17)
    at Record.TemplateBlock.applyBlock (/home/qiuxy/.gitbook/versions/3.1.1/lib/models/templateBlock.js:210:21)
    at /home/qiuxy/.gitbook/versions/3.1.1/lib/output/getModifiers.js:56:33
    at /home/qiuxy/.gitbook/versions/3.1.1/lib/output/modifiers/highlightCode.js:47:24
    at /home/qiuxy/.gitbook/versions/3.1.1/lib/output/modifiers/editHTMLElement.js:11:16
    at /home/qiuxy/.gitbook/versions/3.1.1/lib/utils/promise.js:35:16
    at /home/qiuxy/.gitbook/versions/3.1.1/lib/utils/promise.js:21:20
    at _fulfilled (/home/qiuxy/.gitbook/versions/3.1.1/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/qiuxy/.gitbook/versions/3.1.1/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/qiuxy/.gitbook/versions/3.1.1/node_modules/q/q.js:796:13)
```

**Comment by qiuggv** [comment]
while file "dai_ma_sheng_cheng_shi_yong_zhi_nan.md" include
```
<catalog module="com.alogic.rpc.spring.PackageCatalog"
                package="com.ctg.pasp.demo.app.facade.impl"
                path="/ctgae"
                name="inner"/>
```
will throw this error

**Comment by SamyPesse** [comment]
Can you paste me the content of `gong_gong_kai_fa_kuang_jia/hou_duan_kai_fa_kuang_jia/dai_ma_sheng_cheng_shi_yong_zhi_nan.md` please.

**Comment by davidfhaines** [comment]
Same issue here. Sample content that triggers the error:

```
# Why no backticks?

Inline code blocks, `like so`, cause the error. As do regular code blocks. Seems unhappy with any backtick.
```
These issues do not occur with legacy version 2.6.7.
