### ISSUE TITLE
Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by onedayl** [GitbookIO/gitbook#1496]
**Env**
- CLI version: 2.3.0
- GitBook version: 3.2.0
- OS: MacOS 10.11.6

cannot  serve or build a gitbook, the error message shows:
```
zkcms git:master ❯ gitbook serve --debug                                                                        ⏎ ✹
Live reload server started on port: 35729
Press CTRL+C to quit ...


TypeError: Cannot read property 'file' of undefined
TypeError: Cannot read property 'file' of undefined
    at /Users/onedayl/.gitbook/versions/3.2.0/lib/parse/parseConfig.js:44:19
    at _fulfilled (/Users/onedayl/.gitbook/versions/3.2.0/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/onedayl/.gitbook/versions/3.2.0/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/onedayl/.gitbook/versions/3.2.0/node_modules/q/q.js:796:13)
    at /Users/onedayl/.gitbook/versions/3.2.0/node_modules/q/q.js:604:44
    at runSingle (/Users/onedayl/.gitbook/versions/3.2.0/node_modules/q/q.js:137:13)
    at flush (/Users/onedayl/.gitbook/versions/3.2.0/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I‘ve checked `book.json` and `SUMMARY.md`, but noting seems wrong.
The weird thing is, I can serve or build successfully on version 2.6.6 without changing anything:
```
zkcms git:master ❯ gitbook serve --gitbook=2.6.6
info: loading book configuration....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: load plugin gitbook-plugin-livereload ....OK
info: >> 4 plugins loaded
info: start generation with website generator
info: clean website generator
info: OK
info: generation is finished

Starting server ...
Serving book on http://localhost:4000
```

**Comment by JonathanMH** [comment]
For me it was the rule `book*` in my `.gitignore` file
more info: http://jonathanmh.com/solved-gitbook-typeerror-cannot-read-property-file-of-undefined/

**Comment by sinameraji** [comment]
Thanks JonathanMH
