### ISSUE TITLE
gitbook pdf failes

### ISSUE THREAD

**Issue by Lerentis** [GitbookIO/gitbook#1538]
I don't know if i'm doing something wrong but i followed [this](https://toolchain.gitbook.com/ebook.html) guide to create a pdf out of my GitBook Project.
### What is the current behavior?

running

```
gitbook pdf ./ ./
```

results in an error and creates a nur fully rendered pdf in /tmp

```
gitbook pdf ./ ./ --debug
info: 7 plugins are installed 
info: 6 explicitly listed 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 4 pages 
info: found 5 asset files 

EbookError: Error during ebook generation: 1% Converting input to HTML...
InputFormatPlugin: HTML Input running
on /tmp/tmp-21411FZsaiA2J9Vpy/SUMMARY.html
Language not specified
Creator not specified
Building file list...
Normalizing filename cases
Rewriting HTML links
34% Running transforms on ebook...
Merging user specified metadata...
Detecting structure...
    Detected chapter: Introduction
    Detected chapter: Hardware
    Detected chapter: Software
    Detected chapter: Clients
Auto generated TOC with 4 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
73% Rendered SUMMARY.html
80% Rendered index.html
86% Rendered hardware.html
93% Rendered software.html
100% Rendered clients.html
Rendered PDF in 2.57199 seconds:
PDF output written to /tmp/tmp-21411FZsaiA2J9Vpy/index.pdf
Output saved to   /tmp/tmp-21411FZsaiA2J9Vpy/index.pdf


EbookError: Error during ebook generation: 1% Converting input to HTML...
InputFormatPlugin: HTML Input running
on /tmp/tmp-21411FZsaiA2J9Vpy/SUMMARY.html
Language not specified
Creator not specified
Building file list...
Normalizing filename cases
Rewriting HTML links
34% Running transforms on ebook...
Merging user specified metadata...
Detecting structure...
    Detected chapter: Introduction
    Detected chapter: Hardware
    Detected chapter: Software
    Detected chapter: Clients
Auto generated TOC with 4 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
73% Rendered SUMMARY.html
80% Rendered index.html
86% Rendered hardware.html
93% Rendered software.html
100% Rendered clients.html
Rendered PDF in 2.57199 seconds:
PDF output written to /tmp/tmp-21411FZsaiA2J9Vpy/index.pdf
Output saved to   /tmp/tmp-21411FZsaiA2J9Vpy/index.pdf


    at createError (/home/lerentis/.gitbook/versions/3.2.0/node_modules/error/typed.js:31:22)
    at Object.createError [as EbookError] (/home/lerentis/.gitbook/versions/3.2.0/node_modules/error/wrapped.js:88:19)
    at /home/lerentis/.gitbook/versions/3.2.0/lib/output/ebook/onFinish.js:74:25
    at _rejected (/home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:844:24)
    at /home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:870:30
    at Promise.when (/home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:788:41)
    at /home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:604:44
    at runSingle (/home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:137:13)
    at flush (/home/lerentis/.gitbook/versions/3.2.0/node_modules/q/q.js:125:13)
```

Versions and additional Informations:

```
gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.0
```

```
calibre --version
calibre (calibre 2.68)
```

```
uname -a 
Linux Muninn 4.7.4-1-ARCH #1 SMP PREEMPT Thu Sep 15 15:24:29 CEST 2016 x86_64 GNU/Linux
```
### What is the expected behavior?

A fully rendered pdf file in the current directory

**Comment by Vorlif** [comment]
Same problem here

```
gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
```

```
calibre --version
calibre (calibre 2.70)
```

```
uname -a
Linux test 4.4.25-1-lts #1 SMP Sun Oct 16 19:53:04 CEST 2016 x86_64 GNU/Linux
```
