### ISSUE TITLE
Gitbook failed to start if there is a `*` in `.gitignore`

### ISSUE THREAD

**Issue by ghost** [GitbookIO/gitbook#1657]
### What is the current behavior?

Reproduction:

```bash
echo '*' > .gitignore
gitbook serve --debug
```

or 
```bash
echo '*' > .gitignore
gitbook pdf --debug
```

Result:
```
Live reload server started on port: 35729
Press CTRL+C to quit ...


TypeError: Cannot read property 'file' of undefined
TypeError: Cannot read property 'file' of undefined
    at /home/karl/.gitbook/versions/3.2.2/lib/parse/parseConfig.js:44:19
    at _fulfilled (/home/karl/.gitbook/versions/3.2.2/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/karl/.gitbook/versions/3.2.2/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/karl/.gitbook/versions/3.2.2/node_modules/q/q.js:796:13)
    at /home/karl/.gitbook/versions/3.2.2/node_modules/q/q.js:604:44
    at runSingle (/home/karl/.gitbook/versions/3.2.2/node_modules/q/q.js:137:13)
    at flush (/home/karl/.gitbook/versions/3.2.2/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Gitbook version:
```
gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.2
```

Tested OS:
Ubuntu 16.04 LTS, Mac OS X 10.11 El Capitan

### What is the expected behavior?

Gitbook should start, no matter what's in the `.gitignore` file.

**Comment by codylindley** [comment]
Wait, really. Ah, this might be my issue.

**Comment by mateodelnorte** [comment]
Why is gitbook ignoring things that are ignored in .gitignore? Why doesn't it just go with whatever is on the file system?

**Comment by shriramks** [comment]
Having the same issue,

```
gitbook serve --debug
Live reload server started on port: 35729
Press CTRL+C to quit ...


TypeError: Cannot read property 'file' of undefined
TypeError: Cannot read property 'file' of undefined
    at /Users/firefly/.gitbook/versions/3.2.2/lib/parse/parseConfig.js:44:19
    at _fulfilled (/Users/firefly/.gitbook/versions/3.2.2/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/firefly/.gitbook/versions/3.2.2/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/firefly/.gitbook/versions/3.2.2/node_modules/q/q.js:796:13)
    at /Users/firefly/.gitbook/versions/3.2.2/node_modules/q/q.js:604:44
    at runSingle (/Users/firefly/.gitbook/versions/3.2.2/node_modules/q/q.js:137:13)
    at flush (/Users/firefly/.gitbook/versions/3.2.2/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Checked and tried previous solutions to this type of issue,
1) https://github.com/GitbookIO/gitbook/issues/1496: there is no  "*" in my .gitignore
2) https://github.com/GitbookIO/gitbook/issues/135: my SUMMARY.md does not have any lines between them

Is there anything else I need to check?

OS: macOS Sierra 10.12.4
CLI version: 2.3.0
GitBook version: 3.2.2
