### ISSUE TITLE
WTF: Cannot find module 'internal/fs'

### ISSUE THREAD

**Issue by chai2010** [GitbookIO/gitbook#1774]
```
node -v
v7.7.3

gitbook --version
CLI version: 2.3.0
GitBook version: 2.6.7

gitbook build
Error loading version latest: Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (C:\Users\chai\.gitbook\versions\2.6.7\node_modules\npm\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

TypeError: Cannot read property 'commands' of null
```

**Comment by avh4** [comment]
The comments in https://github.com/nodejs/node/issues/9377 suggest that this happens when an old version of npm is used with a new version of node.

Notably, `gitbook-cli@2.3.0` depends on `npmi@1.0.1` which depends on `npm@2.15.12` (the latest version is 4.6.1).  I suspect that `npm@2.x` is incompatible with `node@7.x`

**Comment by avh4** [comment]
Playing with this further, it appears I also had `GitBook version: 2.6.x`, and was seeing this error with `gitbook init`.

I did `gitbook update` and now have `GitBook version: 3.2.2`, and I am no longer am getting this error.

**Comment by pajtai** [comment]
I did a gitbook update and now have 3.2.2, and I'm still getting this error.

Node v8.1.0
Npm v5.0.3
Gitbook v3.2.2
