### ISSUE TITLE
details and summary tags: TypeError: $ is not a function

### ISSUE THREAD

**Issue by SheetJSDev** [GitbookIO/gitbook#1788]
Details-summary markdown trip up the markdown parser:

```xml
<details>
    <summary>Foo</summary>

Bar

</details>
```

Github uses this form [to show collapsible groups](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)

Debug output:

```
$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.2
$ gitbook serve --log=debug --debug
TypeError: $ is not a function
    at parseReadme (/Users/whoknows/.gitbook/versions/3.2.2/node_modules/gitbook-markdown/node_modules/gitbook-html/lib/readme.js:14:16)
    at /Users/whoknows/.gitbook/versions/3.2.2/node_modules/gitbook-markdown/node_modules/gitbook-html/lib/index.js:18:19
    at Record.Parser.parseReadme (/Users/whoknows/.gitbook/versions/3.2.2/lib/models/parser.js:31:20)
    at /Users/whoknows/.gitbook/versions/3.2.2/lib/parse/parseStructureFile.js:28:27
    at _fulfilled (/Users/whoknows/.gitbook/versions/3.2.2/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/whoknows/.gitbook/versions/3.2.2/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/whoknows/.gitbook/versions/3.2.2/node_modules/q/q.js:796:13)
    at /Users/whoknows/.gitbook/versions/3.2.2/node_modules/q/q.js:604:44
    at runSingle (/Users/whoknows/.gitbook/versions/3.2.2/node_modules/q/q.js:137:13)
    at flush (/Users/whoknows/.gitbook/versions/3.2.2/node_modules/q/q.js:125:13)
```

**Comment by SheetJSDev** [comment]
The simplest workaround is to strip the tags:

```bash
<old_md_file.md grep -vE "(details|summary)>" > new_md_file.md
```
