### ISSUE TITLE
Error: Cannot find module 'gitbook-html'

### ISSUE THREAD

**Issue by creaux** [GitbookIO/gitbook#1792]
I just installed gitbook latest stable version 3.2.2.

I've got following error message in console when I run `gitbook init`.

```bash
Error loading version latest: Error: Cannot find module 'gitbook-html'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/username/.gitbook/versions/3.2.2/node_modules/gitbook-markdown/lib/index.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

TypeError: Cannot read property 'commands' of null
```

This is version according your NOTICE:

```
GitBook:

CLI version: 2.3.0
GitBook version: 3.2.2

OS:

System Version: macOS 10.12.4 (16E195)
Kernel Version: Darwin 16.5.0

NodeJS and npm:

Node: v6.10.3
npm: 3.10.10
```

As well using `nvm`. 

So I even tried with `NodeJS v6.4.0`, `NodeJS v7.10.0`. 

Looks to me like its maybe `nvm` issue and that's a shame as I can't simply uninstall any idea?

**Comment by creaux** [comment]
Solution:

Run `gitbook fetch` it installs latest version of dependencies perhaps?! But works then with `gitbook init`.
