### ISSUE TITLE
Error building PDF, MOBI or EPUB: EbookError: Error during ebook generation: The command line is too long.

### ISSUE THREAD

**Issue by looeee** [GitbookIO/gitbook#2030]
### What is the current behavior?

On windows, with a variety of command lines: CMD with and without admin, powershell, cygwin.
Tested with gitbook 3.2.3. The commands `gitbook build` and `gitbook serve` work fine. 

However `gitbook pdf ./ ./book.pdf -d` gives the following error, as do equivalent epub and mobi commands:

```bash
EbookError: Error during ebook generation: The command line is too long.


    at createError (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\error\typed.js:31:22)
    at Object.createError [as EbookError] (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\error\wrapped.js:88:19)
    at C:\Users\looee\.gitbook\versions\3.2.3\lib\output\ebook\onFinish.js:74:25
    at _rejected (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:844:24)
    at C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:788:41)
    at C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:604:44
    at runSingle (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:137:13)
    at flush (C:\Users\looee\.gitbook\versions\3.2.3\node_modules\q\q.js:125:13)
```

**Comment by looeee** [comment]
Testing with older versions - reverting to 3.1.0 fixes the issue, but it's still present in 3.2.0.

**Comment by HaidongSong** [comment]
win10下安装ebook-convert没有提示出错，安装完后执行：
```
ebook-convert --version
bash: ebook-convert: command not found

**Comment by HaidongSong** [comment]
win10下安装ebook-convert，安装没有提示出错用cnpm install ebook-convert -g，安装完后执行：
```
ebook-convert --version
bash: ebook-convert: command not found
```


直接运行
```
gitbook pdf
info: loading book configuration....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-search ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: >> 4 plugins loaded
info: start generation with pdf generator
info: clean pdf generatorOK
info: write SUMMARY.html
info: start conversion to pdf ....ERROR

Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "ebook-convert C:\Users\haidong.000\AppData\Local\Temp\tmp-4988kwr9gts\SUMMARY.html C:\Users\haidong.000\AppData\Local\Temp\tmp-4988kwr9gts\index.pdf --title="My Awesome Book" --comments="以京东金融app为实战项目，学习组件化思维。" --language="en" --book-producer="GitBook" --publisher="GitBook" --chapter="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter ')]" --level1-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-1 ')]" --level2-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-2 ')]" --level3-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-3 ')]" --no-chapters-in-toc --max-levels="1" --breadth-first --chapter-mark="pagebreak" --page-breaks-before="/" --margin-left="62" --margin-right="62" --margin-top="56" --margin-bottom="56" --pdf-default-font-size="12" --pdf-mono-font-size="12" --paper-size="a4" --pdf-header-template="<html>
    <body style=\"font-family: sans-serif; color: #000; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">
        <div class=\"pdf-header\" style=\"margin-top: 20px; color: #aaa; padding-bottom: 10px; border-bottom: 1px solid #eee;\">
            <span>_TITLE_</span>
        </div>
    </body>
</html>" --pdf-footer-template="<html>
    <body style=\"font-family: sans-serif; color: #000; text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\">
        <div class=\"pdf-footer\" style=\"margin-top: 20px; color: #aaa; padding-top: 10px; border-top: 1px solid #eee;\">
            <span>_SECTION_</span>
            <span class=\"footer-pages-count\" style=\"float: right;\">_PAGENUM_</span>
        </div>
    </body>
</html>" --pdf-sans-family="Arial""
'ebook-convert' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```
