### ISSUE TITLE
Error: TypeError: speech.processExpression is not a function

### ISSUE THREAD

**Issue by loretoparisi** [GitbookIO/gitbook#2077]
```
$ gitbook --version
CLI version: 2.3.2
GitBook version: 3.2.0
```

I get this error:

```
ip-192-168-22-127:userguide loretoparisi$ gitbook pdf ./ ./turicreate_userguide.pdf
info: 10 plugins are installed 
info: 9 explicitly listed 
info: loading plugin "collapsible-menu"... OK 
info: loading plugin "anchors"... OK 
info: loading plugin "mathjax"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 62 pages 
info: found 110 asset files 
warn: "sections" property is deprecated, use page.content instead 
warn: "this.generator" property is deprecated, use "this.output.name" instead 
warn: "navigation" property is deprecated 
warn: "book" property is deprecated, use "this" directly instead 
warn: "options" property is deprecated, use config.get(key) instead 
Error: TypeError: speech.processExpression is not a function
    at GetSpeech (/Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax-node/lib/mj-single.js:540:29)
    at Function.execute (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.call (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///Users/loretoparisi/Documents/Projects/AI/turicreate/userguide/node_modules/mathjax/unpacked/MathJax.js:348:50)
```

**Comment by kachkaev** [comment]
This is probably a duplicate of https://github.com/GitbookIO/gitbook/issues/1875

**Comment by loretoparisi** [comment]
@kachkaev confirmed! closing
