### ISSUE TITLE
Template render error: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by li2** [GitbookIO/gitbook#2079]
### What is the current behavior?

I have searched several issues with similar title "Template render error", these issues have much more details with line & column number, such as `[Line 85, Column 43] unexpected token`, however, my issue doesn't have such detail, I have no idea how to fix it. Could u please help to fix it? thanks in advance.

```sh
╰─ gitbook -d serve                                                                                                                                 1 ↵  1709  14:57   02.07
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 17 plugins are installed
info: 11 explicitly listed
info: loading plugin "tags"... OK
info: loading plugin "expandable-chapters"... OK
info: loading plugin "docsearch"... OK
info: loading plugin "page-toc"... OK
info: loading plugin "back-to-top-button"... OK
info: loading plugin "copy-code-button"... OK
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 137 pages
info: found 62 asset files
error: error while generating page "Network/retrofit-tutorial.md":

Template render error: (/Users/weiyi/GitBook/Library/li2/android-programming-journey/Network/retrofit-tutorial.md)
  SyntaxError: Invalid or unexpected token
Template render error: (/Users/weiyi/GitBook/Library/li2/android-programming-journey/Network/retrofit-tutorial.md)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/nunjucks/src/environment.js:327:21)
    at Promise.apply (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/q/q.js:788:41)
    at /Users/weiyi/.gitbook/versions/3.2.3/node_modules/q/q.js:1391:14
    at runSingle (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/q/q.js:137:13)
    at flush (/Users/weiyi/.gitbook/versions/3.2.3/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
╭─ ~/Git…ook/Lib…ary/li2/android-programming-journey   master ↑1 
╰─                                                                                                                                                  1 ↵  1709  14:59   02.07
╭─ ~/Git…ook/Lib…ary/li2/android-programming-journey   master 
╰─ gitbook -V                                                                                                                                       1 ↵  1709  15:00   02.07
CLI version: 2.3.2
GitBook version: 3.2.3

MAC 10.13.3
```

#### For legacy.gitbook.com
https://li2.gitbooks.io/android-programming-journey/content/Network/

**Comment by li2** [comment]
Finally fixed by examining each row in turn, hope that `gitbook -d` could be able to give much more details about `unexpected token`, thanks

<img width="925" alt="gitbook-syntaxerror- invalid or unexpected token" src="https://user-images.githubusercontent.com/6058601/42512183-4a4185fc-8497-11e8-904f-5005690b8ab4.png">
