### ISSUE TITLE
fetch latest fetches last published version instead of latest

### ISSUE THREAD

**Issue by ptacekj** [GitbookIO/gitbook#2138]
### What is the current behavior?
when trying to fetch **latest** gitbook version I get 2.6.8 which is most likely the **last** version published (17 hrs ago). See log below. The installation also fails but I'm not sure if that is gitbooks' problem or problem of my repository.

node version **latest 8.9**
commands
```
npm install gitbook-cli -g
gitbook fetch latest
gitbook install
```
Log
```
$ npm install gitbook-cli -g
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.17.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
/usr/local/bin/gitbook -> /usr/local/lib/node_modules/gitbook-cli/bin/gitbook.js
+ gitbook-cli@2.3.2
added 578 packages in 12.388s
$ gitbook fetch latest
Installing GitBook 2.6.8
gitbook@2.6.8 ../../../tmp/tmp-26HORhJJGkf0cs/node_modules/gitbook
├── bash-color@0.0.3
├── escape-string-regexp@1.0.3
├── nunjucks-filter@1.0.0
├── gitbook-plugin-livereload@0.0.1
├── gitbook-plugin-sharing@1.0.1
├── gitbook-plugin-fontsettings@1.0.2
├── github-slugid@1.0.0
├── nunjucks-autoescape@1.0.0
├── jsonschema@1.0.2
├── spawn-cmd@0.0.2
├── q@1.0.1
├── json-schema-defaults@0.1.1
├── graceful-fs@3.0.5
├── semver@5.0.1
├── urijs@1.17.0
├── crc@3.2.1
├── tmp@0.0.24
├── dom-serializer@0.1.0 (domelementtype@1.1.3, entities@1.1.1)
├── merge-defaults@0.2.1 (lodash@2.4.2)
├── resolve@0.6.3
├── npmi@0.1.1 (semver@4.3.6)
├── send@0.2.0 (fresh@0.2.4, range-parser@1.0.3, mime@1.2.11, debug@4.1.0)
├── i18n@0.5.0 (sprintf@0.1.5, mustache@3.0.0, debug@3.2.6)
├── request@2.51.0 (tunnel-agent@0.4.3, forever-agent@0.5.2, aws-sign2@0.5.0, caseless@0.8.0, oauth-sign@0.5.0, stringstream@0.0.6, json-stringify-safe@5.0.1, mime-types@1.0.2, qs@2.3.3, node-uuid@1.4.8, combined-stream@0.0.7, http-signature@0.10.1, tough-cookie@2.4.3, form-data@0.2.0, hawk@1.1.1, bl@0.9.5)
├── fs-extra@0.16.5 (jsonfile@2.4.0, rimraf@2.6.2)
├── tiny-lr@0.2.1 (parseurl@1.3.2, livereload-js@2.3.0, qs@5.1.0, debug@2.2.0, body-parser@1.14.2, faye-websocket@0.10.0)
├── nunjucks@2.2.0 (asap@2.0.6, optimist@0.6.1)
├── fstream-ignore@1.0.2 (inherits@2.0.3, minimatch@2.0.10, fstream@1.0.11)
├── chokidar@1.0.6 (arrify@1.0.1, is-glob@1.1.3, path-is-absolute@1.0.1, async-each@0.1.6, is-binary-path@1.0.1, glob-parent@1.3.0, readdirp@1.4.0, anymatch@1.3.2)
├── cheerio@0.19.0 (entities@1.1.1, css-select@1.0.0, htmlparser2@3.8.3)
├── gitbook-plugin-search@1.1.0 (lunr@0.5.12)
├── gitbook-parsers@0.8.9 (q@1.5.1, gitbook-restructuredtext@0.2.3, gitbook-markdown@0.5.3, gitbook-asciidoc@0.2.4)
├── gitbook-plugin-highlight@1.0.3 (highlight.js@8.8.0)
├── lodash@3.10.1
├── juice@1.5.0 (commander@2.3.0, slick@1.12.1, batch@0.5.2, cssom@0.3.0, web-resource-inliner@1.1.4)
└── npm@2.4.1

GitBook 2.6.8 has been installed
$ gitbook install
Error loading version latest: Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/root/.gitbook/versions/2.6.8/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

TypeError: Cannot read property 'commands' of null
ERROR: Job failed: exit code 1
```
### What is the expected behavior?
When using `fetch latest` I should get version 3.2.2 as I did up untill Oct 10, 04:05PM GMT+2

**Comment by detj** [comment]
Facing this same issue too. I fixed it by omitting `gitbook fetch latest` as it installs 3.2.3 by default. Will this have some other impact ? not sure about that.
