### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by eljefe6a** [GitbookIO/gitbook#454]
When I do a build with my images directory in the same directory as SUMMARY.md I get the follow errors:

```
Jesses-MacBook-Pro:Modern_Application_Architecture jesse$ gitbook build --format ebook
Starting build ...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/jesse/repos/Hadoop/classes/Modern_Application_Architecture/images/cloud_images/btree.png'
Jesses-MacBook-Pro:Modern_Application_Architecture jesse$ gitbook build
Starting build ...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/jesse/repos/Hadoop/classes/Modern_Application_Architecture/_book/images/cloud_images/amazon_weekly_traffic_waste.png'
Jesses-MacBook-Pro:Modern_Application_Architecture jesse$ gitbook build --format ebook
Starting build ...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/jesse/repos/Hadoop/classes/Modern_Application_Architecture/images/cloud_images/openstack_screenshot_services.png'
Jesses-MacBook-Pro:Modern_Application_Architecture jesse$ gitbook build --format ebook -o test
Starting build ...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/jesse/repos/Hadoop/classes/Modern_Application_Architecture/class_requirements.txt'
```

Notice that the file that it errors out on is different depending on the build command. Moving this directory out prevents this issue. I've tried to make a test case by manually creating directories and files and I can't  get a clean, repeatable way to replicate this.

Are there any known issues that might be related? [This person](https://github.com/GitbookIO/gitbook/issues/211) reported a similar error, but his fix of specifying a new output directory doesn't work for me.

For now, I am keeping the images directory as a peer of the directory with SUMMARY.md.

**Comment by cmoulliard** [comment]
I also get the same error when I launch `gitbook serve` with a simple SUMMARY.md structure. See the attached picture. All the *.md files are empty excepted the SUMMARY.md

![screenshot 2015-05-06 10 50 18](https://cloud.githubusercontent.com/assets/463790/7490109/d0af6a62-f3dd-11e4-9b26-34d5dd046056.png)

Error: 

`````
gitbook serve
Press CTRL+C to quit ...

Live reload server started on port: 35729
Starting build ...
Successfully built!

Starting server ...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1127:5)
    at /usr/local/lib/node_modules/gitbook/bin/server.js:83:22
    at _fulfilled (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/gitbook/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/gitbook/node_modules/q/q.js:108:17)
````

**Comment by SamyPesse** [comment]
@cmoulliard `EADDRINUSE` is an error when the port `4000` used by `gitbook serve` is already used by another program.

**Comment by cmoulliard** [comment]
I confirm. I don't have this error when using another port.
