### ISSUE TITLE
PDF build failing continuously 

### ISSUE THREAD

**Issue by nasirkhan** [GitbookIO/gitbook#585]
@AaronO thanks for your previous fix.

Now there is an another issue, the PDF build is failing each time. Here i have added one of the failed builds and the output. and from the screenshot you will find the series of failed builds. 

`Build 6bd7b0cd0e`

```
Tweaking book.json
Installing plugins
Install plugins in /tmp/book
Install plugin autocover from npm (gitbook-plugin-autocover) with version *
Install plugin mathjax from npm (gitbook-plugin-mathjax) with version *
gitbook-plugin-mathjax@0.0.6 node_modules/gitbook-plugin-mathjax
Successfully installed plugins!
Starting Xvfb
Building PDF, will upload
Starting build ...
Command failed: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Traceback (most recent call last):
  File "site.py", line 51, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 360, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1195, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 145, in convert
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 232, in convert_text
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 258, in write
  File "site-packages/calibre/ebooks/pdf/render/from_html.py", line 244, in dump
Exception: PDF Output failed, see log for details
 1% Converting input to HTML...
InputFormatPlugin: HTML Input running
on /tmp/tmp-36nataycw/SUMMARY.html
Language not specified
Building file list...
IgnoreFile(u'/tmp/tmp-36nataycw/manuscript/\u0995\u09bf\u09ad\u09be\u09ac\u09c7 \u0989\u0987\u0995\u09bf\u09aa\u09bf\u09a1\u09bf\u09df\u09be\u09b0 \u09a8\u09bf\u09ac\u09a8\u09cd\u09a7 \u09b8\u09ae\u09cd\u09aa\u09be\u09a6\u09a8\u09be  \u0995\u09b0\u09ac\u09c7\u09a8.txt is a binary file',)
Normalizing filename cases
Rewriting HTML links
Ignoring link to text file u'./manuscript/\u0995\u09bf\u09ad\u09be\u09ac\u09c7 \u0989\u0987\u0995\u09bf\u09aa\u09bf\u09a1\u09bf\u09df\u09be\u09b0 \u09a8\u09bf\u09ac\u09a8\u09cd\u09a7 \u09b8\u09ae\u09cd\u09aa\u09be\u09a6\u09a8\u09be  \u0995\u09b0\u09ac\u09c7\u09a8.txt'
Ignoring link to text file u'manuscript/\u0995\u09bf\u09ad\u09be\u09ac\u09c7 \u0989\u0987\u0995\u09bf\u09aa\u09bf\u09a1\u09bf\u09df\u09be\u09b0 \u09a8\u09bf\u09ac\u09a8\u09cd\u09a7 \u09b8\u09ae\u09cd\u09aa\u09be\u09a6\u09a8\u09be  \u0995\u09b0\u09ac\u09c7\u09a8.txt'
Failed to process link: u'http://www.bangladesh.gov.bd]\u0964'
34% Running transforms on ebook...
Merging user specified metadata...
Detecting structure...
	Detected chapter: Introduction
	Detected chapter: উইকিপিডিয়া - কী ও কেনো
	Detected chapter: বাংলা উইকিপিডিয়া
	Detected chapter: উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো
	Detected chapter: উইকিপিডিয়ায় একাউন্ট
	Detected chapter: একাউন্ট তৈরী করা প্রয়োজন কেন
	Detected chapter: ব্যবহারকারী নাম কেমন হওয়া উচিত
	Detected chapter: সম্পাদনা এবং নতুন নিবন্ধ তৈরী
	Detected chapter: সম্পূর্ণ নিবন্ধ সম্পাদনা
	Detected chapter: সম্পাদনা সারাংশ
	Detected chapter: নিবন্ধের অনুচ্ছেদ সম্পাদনা
	Detected chapter: নতুন নিবন্ধ তৈরী করা
	Detected chapter: উইকিপিডিয়ার বিভিন্ন অংশ
	Detected chapter: প্রধান পাতা
	Detected chapter: ইতিহাস
	Detected chapter: আলোচনা পাতা
	Detected chapter: উইকি সিন্ট্যাক্স ব্যবহার করে সম্পাদনা
	Detected chapter: শিরনাম ও অনুচ্ছেদ তৈরী
	Detected chapter: লেখার ধরণ পরিবর্তন
	Detected chapter: উইকিপিডিয়ানদের পারস্পরিক যোগাযোগ
	Detected chapter: শিষ্টাচার
	Detected chapter: কপিরাইট
	Detected chapter: বিশ্বকোষীয় ধাঁচে লেখা
Auto generated TOC with 23 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
68% Rendered SUMMARY.html
69% Rendered index.html
71% Rendered uikipiddiy'aa - kii o keno.html
72% Rendered baaNlaa uikipiddiy'aa.html
73% Rendered uikipiddiy'aa nibndher saadhaarnn kaatthaamo.html
75% Rendered uikipiddiy'aay'  ekaauntt.html
76% Rendered ekaauntt tairii kraa pry'ojn ken.html
78% Rendered bybhaarkaarii  naam kemn hoy'aa ucit.html
79% Rendered smpaadnaa  ebN ntun nibndh tairii.html
80% Rendered smpuurnn nibndh smpaadnaa.html
82% Rendered smpaadnaa  saaraaNsh.html
83% Rendered nibndher anucched smpaadnaa.html
84% Rendered ntun nibndh tairii kraa.html
86% Rendered uikipiddiy'aar  bibhinn aNsh.html
87% Rendered prdhaan paataa.html
89% Rendered itihaas.html
90% Rendered aalocnaa paataa.html
91% Rendered uiki sinttyaaks bybhaar kre smpaadnaa.html
93% Rendered shirnaam o anucched tairii.html
94% Rendered lekhaar dhrnn pribrtn.html
95% Rendered uikipiddiy'aander paarsprik yogaayog.html
97% Rendered shissttaacaar.html
98% Rendered kpiraaitt.html
100% Rendered bishbkossiiy' dhaaNce lekhaa.html
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 140, in end
  File "site-packages/calibre/ebooks/pdf/render/serialize.py", line 509, in end
  File "site-packages/calibre/ebooks/pdf/render/links.py", line 81, in add_links
  File "urlparse.py", line 143, in urlparse
  File "urlparse.py", line 191, in urlsplit
ValueError: Invalid IPv6 URL
```
![screenshot-www gitbook com 2015-02-05 14-07-08](https://cloud.githubusercontent.com/assets/396987/6056809/6a9753fe-ad40-11e4-8f50-d722e553fe9b.jpeg)

**Comment by SamyPesse** [comment]
@nasirkhan not related to the PDF error but: what browser are you using? It looks like there is an error of position of the header.

**Comment by nasirkhan** [comment]
Usually i use Firefox from Windows8 and Ubuntu 14.10
The previous screenshot was form Firefox on Windows 8. I scrolled the page a little before taking the screenshot, and that is why the image looks like that. see the new screenshots below. 

![1423148479498screensave](https://cloud.githubusercontent.com/assets/396987/6062560/e5e3af6e-ad7a-11e4-9886-5170c31365c5.png)
![screenshot-www gitbook com 2015-02-05 20-56-27](https://cloud.githubusercontent.com/assets/396987/6062565/ee71957e-ad7a-11e4-8993-90ec4a3e8c8d.jpeg)

**Comment by SamyPesse** [comment]
Ok thanks

**Comment by nasirkhan** [comment]
Anyone is working on it? the pdf of my book is showing a very old version of the book.

**Comment by AaronO** [comment]
Hi @nasirkhan I'm working on it today, 

Expect to see a result today or this weekend. I'll keep you updated :+1:

**Comment by nasirkhan** [comment]
thanks in advance :+1:

**Comment by nasirkhan** [comment]
still facing the PDF build issue, here is the build id and output 

*Build 1977d7aafc*

```
Downloading source
Extracting source
Current version is 2.0.0-alpha.8
Tweaking book.json
Installing plugins
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: 1 plugins to install 
info: No version specified, resolve plugin autocover 
info: install plugin autocover from npm (gitbook-plugin-autocover) with version 1.2.1 
info: >> plugin autocover installed with success 

Done, without error
Starting Xvfb
Building PDF, will upload
info: loading book configuration....
warn: you should specify a gitbook version to use in your book.json, for example: 2.x.x 
info: OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 1 plugins loaded 
info: start generation with pdf generator 
info: clean pdf generatorOK 
warn: Language 'bn' is not available as a layout locales (en, de, es, fr, it, no, pt, ru, zh-cn, zh-tw) 
info: processing README.md 0% 
info: processing manuscript/অভ্যন্তরীণ ও বহিঃসংযোগ তৈরী.md 3% 
info: processing manuscript/আপলোড উইজার্ডের মাধ্যমে আপলোড করা.md 5% 
info: processing manuscript/আলোচনা পাতা.md 8% 
info: processing manuscript/ইতিহাস.md 10% 
info: processing manuscript/উইকি সিন্ট্যাক্স ব্যবহার করে সম্পাদনা.md 13% 
info: processing manuscript/উইকিপিডিয়া - কী ও কেনো.md 15% 
info: processing manuscript/উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো.md 18% 
info: processing manuscript/উইকিপিডিয়া মোবাইল অ্যাপ ব্যবহার পদ্ধতি.md 21% 
info: processing manuscript/উইকিপিডিয়া মোবাইল অ্যাপ.md 23% 
info: processing manuscript/উইকিপিডিয়ানদের পারস্পরিক যোগাযোগ.md 26% 
info: processing manuscript/উইকিপিডিয়ার  বিভিন্ন অংশ.md 28% 
info: processing manuscript/উইকিপিডিয়ায়  একাউন্ট.md 31% 
info: processing manuscript/উইকিমিডিয়া কমন্স.md 33% 
info: processing manuscript/উইকিমিডিয়া কমন্সে ছবি আপলোডের নিয়ম.md 36% 
info: processing manuscript/উইকিমিডিয়া বাংলাদেশ.md 38% 
info: processing manuscript/একাউন্ট তৈরী করা প্রয়োজন কেন.md 41% 
info: processing manuscript/কপিরাইট.md 44% 
info: processing manuscript/কিভাবে উইকিপিডিয়ার নিবন্ধ সম্পাদনা  করবেন.md 46% 
info: processing manuscript/ছক বা টেবিল তৈরী.md 49% 
info: processing manuscript/ছবি আপলোড করার পদ্ধতি.md 51% 
info: processing manuscript/ছবি সংযোজন.md 54% 
info: processing manuscript/তথ্যসূত্র সংযোজন.md 56% 
info: processing manuscript/তালিকা তৈরী করা.md 59% 
info: processing manuscript/নতুন নিবন্ধ তৈরী করা.md 62% 
info: processing manuscript/নিবন্ধের অনুচ্ছেদ সম্পাদনা.md 64% 
info: processing manuscript/প্রধান পাতা.md 67% 
info: processing manuscript/বাংলা উইকিপিডিয়া.md 69% 
info: processing manuscript/বিশ্বকোষীয় ধাঁচে লেখা.md 72% 
info: processing manuscript/বিষয়শ্রেণী সংযোজন.md 74% 
info: processing manuscript/ব্যবহারকারী  নাম কেমন হওয়া উচিত.md 77% 
info: processing manuscript/ভূমিকা.md 79% 
info: processing manuscript/লেখক পরিচিতি.md 82% 
info: processing manuscript/লেখার ধরণ পরিবর্তন.md 85% 
info: processing manuscript/শিরনাম ও অনুচ্ছেদ তৈরী.md 87% 
info: processing manuscript/শিষ্টাচার.md 90% 
info: processing manuscript/সম্পাদনা  এবং নতুন নিবন্ধ তৈরী.md 92% 
info: processing manuscript/সম্পাদনা  সারাংশ.md 95% 
info: processing manuscript/সম্পূর্ণ নিবন্ধ সম্পাদনা.md 97% 
info: write SUMMARY.html 
info: start conversion to pdf ....ERROR

Error: Command failed: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Traceback (most recent call last):
  File "site.py", line 51, in main
  File "site-packages/calibre/ebooks/conversion/cli.py", line 360, in main
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1195, in run
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 145, in convert
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 232, in convert_text
  File "site-packages/calibre/ebooks/conversion/plugins/pdf_output.py", line 258, in write
  File "site-packages/calibre/ebooks/pdf/render/from_html.py", line 244, in dump
Exception: PDF Output failed, see log for details
 1% Converting input to HTML...
InputFormatPlugin: HTML Input running
on /tmp/tmp-38kdpd2z4/SUMMARY.html
Language not specified
Building file list...
Normalizing filename cases
Rewriting HTML links
Failed to process link: u'http://www.bangladesh.gov.bd]\u0964'
34% Running transforms on ebook...
Merging user specified metadata...
Detecting structure...
	Detected chapter: Introduction
	Detected chapter: ভূমিকা
	Detected chapter: উইকিপিডিয়া - কী ও কেনো
	Detected chapter: বাংলা উইকিপিডিয়া
	Detected chapter: উইকিপিডিয়া নিবন্ধের সাধারণ কাঠামো
	Detected chapter: উইকিপিডিয়ায় একাউন্ট
	Detected chapter: একাউন্ট তৈরী করা প্রয়োজন কেন
	Detected chapter: ব্যবহারকারী নাম কেমন হওয়া উচিত
	Detected chapter: সম্পাদনা এবং নতুন নিবন্ধ তৈরী
	Detected chapter: সম্পূর্ণ নিবন্ধ সম্পাদনা
	Detected chapter: সম্পাদনা সারাংশ
	Detected chapter: নিবন্ধের অনুচ্ছেদ সম্পাদনা
	Detected chapter: নতুন নিবন্ধ তৈরী করা
	Detected chapter: উইকিপিডিয়ার বিভিন্ন অংশ
	Detected chapter: প্রধান পাতা
	Detected chapter: ইতিহাস
	Detected chapter: আলোচনা পাতা
	Detected chapter: কিভাবে উইকিপিডিয়ার নিবন্ধ সম্পাদনা করবেন
	Detected chapter: উইকি সিন্ট্যাক্স ব্যবহার করে সম্পাদনা
	Detected chapter: শিরনাম ও অনুচ্ছেদ তৈরী
	Detected chapter: লেখার ধরণ পরিবর্তন
	Detected chapter: তালিকা তৈরী করা
	Detected chapter: অভ্যন্তরীণ ও বহিঃসংযোগ তৈরী
	Detected chapter: তথ্যসূত্র সংযোজন
	Detected chapter: ছবি সংযোজন
	Detected chapter: ছক বা টেবিল তৈরী
	Detected chapter: বিষয়শ্রেণী সংযোজন
	Detected chapter: উইকিপিডিয়া মোবাইল অ্যাপ
	Detected chapter: উইকিপিডিয়া মোবাইল অ্যাপ ব্যবহার পদ্ধতি
	Detected chapter: বিশ্বকোষীয় ধাঁচে লেখা
	Detected chapter: উইকিমিডিয়া কমন্স
	Detected chapter: উইকিমিডিয়া কমন্সে ছবি আপলোডের নিয়ম
	Detected chapter: আপলোড উইজার্ডের মাধ্যমে আপলোড করা
	Detected chapter: ছবি আপলোড করার পদ্ধতি
	Detected chapter: উইকিপিডিয়ানদের পারস্পরিক যোগাযোগ
	Detected chapter: উইকিমিডিয়া বাংলাদেশ
	Detected chapter: শিষ্টাচার
	Detected chapter: কপিরাইট
	Detected chapter: লেখক পরিচিতি
Auto generated TOC with 39 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating PDF Output...
67% Running PDF Output plugin
67% Rendered SUMMARY.html
68% Rendered index.html
69% Rendered bhuumikaa.html
70% Rendered uikipiddiy'aa - kii o keno.html
71% Rendered baaNlaa uikipiddiy'aa.html
71% Rendered uikipiddiy'aa nibndher saadhaarnn kaatthaamo.html
72% Rendered uikipiddiy'aay'  ekaauntt.html
73% Rendered ekaauntt tairii kraa pry'ojn ken.html
74% Rendered bybhaarkaarii  naam kemn hoy'aa ucit.html
75% Rendered smpaadnaa  ebN ntun nibndh tairii.html
76% Rendered smpuurnn nibndh smpaadnaa.html
76% Rendered smpaadnaa  saaraaNsh.html
77% Rendered nibndher anucched smpaadnaa.html
78% Rendered ntun nibndh tairii kraa.html
79% Rendered uikipiddiy'aar  bibhinn aNsh.html
80% Rendered prdhaan paataa.html
81% Rendered itihaas.html
81% Rendered aalocnaa paataa.html
82% Rendered kibhaabe uikipiddiy'aar nibndh smpaadnaa  krben.html
83% Rendered uiki sinttyaaks bybhaar kre smpaadnaa.html
84% Rendered shirnaam o anucched tairii.html
85% Rendered lekhaar dhrnn pribrtn.html
85% Rendered taalikaa tairii kraa.html
86% Rendered abhyntriinn o bhiHsNyog tairii.html
87% Rendered tthysuutr sNyojn.html
88% Rendered chbi sNyojn.html
89% Rendered chk baa ttebil tairii.html
90% Rendered bissy'shrennii sNyojn.html
90% Rendered uikipiddiy'aa mobaail ayaap.html
91% Rendered uikipiddiy'aa mobaail ayaap bybhaar pddhti.html
92% Rendered bishbkossiiy' dhaaNce lekhaa.html
93% Rendered uikimiddiy'aa kmns.html
94% Rendered uikimiddiy'aa kmnse chbi aaplodder niy'm.html
95% Rendered aaplodd uijaardder maadhyme aaplodd kraa.html
95% Rendered chbi aaplodd kraar pddhti.html
96% Rendered uikipiddiy'aander paarsprik yogaayog.html
97% Rendered uikimiddiy'aa baaNlaadesh.html
98% Rendered shissttaacaar.html
99% Rendered kpiraaitt.html
100% Rendered lekhk priciti.html
Traceback (most recent call last):
  File "site-packages/calibre/ebooks/pdf/render/engine.py", line 140, in end
  File "site-packages/calibre/ebooks/pdf/render/serialize.py", line 509, in end
  File "site-packages/calibre/ebooks/pdf/render/links.py", line 81, in add_links
  File "urlparse.py", line 143, in urlparse
  File "urlparse.py", line 191, in urlsplit
ValueError: Invalid IPv6 URL
```

**Comment by SamyPesse** [comment]
I tried your book locally and it worked for me (pdf). So the problem is probably coming from the ebook-convert version on gitbook.com.

@AaronO, we should use the latest `calibre` version in the beta builder.

**Comment by SamyPesse** [comment]
@nasirkhan Can you do a PR on the branch `version/2` to translate GitBook: https://github.com/GitbookIO/gitbook/tree/version/2.0/theme/i18n

Then you'll be able to specify the book language in the `book.json` (or on gitbook.com book settings) and the PDF will not contain english.

**Comment by nasirkhan** [comment]
do you have any `en.json` file for `i18n`? All the files there are in different language and unfortuanately i could not read any of them.

**Comment by nasirkhan** [comment]
@SamyPesse @AaronO 
can you please tell me how much time will it take to include the new PDF builde? the PDF of my is bool is way more old than the web version. it is very urgent for me, i hope you will understand that. :)

**Comment by SamyPesse** [comment]
I'm bumping gitbook and I'll update the builder with the latest version of calibre, then I'll test your book.

**Comment by SamyPesse** [comment]
I'm still having this issue with a test book in arabic with ebook-convert 2.20.0 :/

**Comment by SamyPesse** [comment]
Oura :rocket: :tada: :balloon: :beers: I found the problem in your book that is causing the error:

In the file `manuscript/internal-and-external-links.md`, there is an invalid link that is converted in html as:

````
<a href="http://www.bangladesh.gov.bd]&#x964;" target="_blank">http://www.bangladesh.gov.bd]&#x964;</a>
```

ebook-convert is failing to convert this.

**Comment by SamyPesse** [comment]
I just proposed a PR on your book to fix this. Also I posted a bug on Calibre Launchpad about this: https://bugs.launchpad.net/calibre/+bug/1429282
