### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by fvcproductions** [GitbookIO/gitbook#719]
# I am unable to export my book into the `epub`, `mobi`, and `PDF` file formats.

I'm not sure why, but I get the following error at the bottom for each:

``` javascript
Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

## Full build details

```javascript
Downloading source
Extracting source
Current version is 2.0.1
Tweaking book.json
Installing plugins
Found package.json and successfuly installed plugins :)
info: 3 plugins to install 
info: No version specified, resolve plugin anchors 
info: install plugin anchors from npm (gitbook-plugin-anchors) with version 0.4.0 
info: >> plugin anchors installed with success 
info: No version specified, resolve plugin youtube 
info: install plugin youtube from npm (gitbook-plugin-youtube) with version 1.1.0 
info: >> plugin youtube installed with success 
info: No version specified, resolve plugin autocover 
info: install plugin autocover from npm (gitbook-plugin-autocover) with version 1.2.1 
info: >> plugin autocover installed with success 

Done, without error
Building MOBI, will upload
info: loading book configuration....OK 
info: load plugin gitbook-plugin-anchors ....
warn: Hook 'page 'used by plugin 'gitbook-plugin-anchors' has been removed or is deprecated 
info: OK 
info: load plugin gitbook-plugin-youtube ....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: >> 3 plugins loaded 
info: start generation with mobi generator 
info: clean mobi generatorOK 
warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be remove in the coming versions 
warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be remove in the coming versions 
warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be remove in the coming versions 
warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be remove in the coming versions 
warn: hook 'page' used by plugin 'gitbook-plugin-anchors' is deprecated, and will be remove in the coming versions 

Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

# The book in question is 
### [https://www.gitbook.com/book/fvcproductions/cs-and-english](https://www.gitbook.com/book/fvcproductions/cs-and-english/).

**Comment by SamyPesse** [comment]
Are you using svgs in your book?

One hypothesis is that your book contains remote svgs (example `http://test.com/file.svg`), in the ebook versions, we are downloading and converting these svgs as pngs, it could fail like this if the remote svg doesn't exist.

**Comment by fvcproductions** [comment]
Yup, you hypothesized correctly!

It turns out there was a remote image that no longer existed.

Thanks so much!
