### ISSUE TITLE
unknown error on generating ebook

### ISSUE THREAD

**Issue by frantic1048** [GitbookIO/gitbook#809]
When I try to generation a ebook file, It just says `Error: Command failed`, I can't find the reason through the command output.

Only the website building is all right.

The book folder is a normal directory, not a git repo.

**Platform**:Linux 4.0.6-1-ARCH

**ebook-convert**: ebook-convert (calibre 2.31.0)

**book.json**:

``` json
{
  "title": "Robot 文档",
  "description": "Robot 的思路与实现",
  "language": "zh-cn",
  "author" : "Microtaku",
  "gitbook": ">=2.0.0",
  "extension": "pdf",
  "structure": {
    "readme": "README.md"
  },
  "links": {
    "sidebar": null,
    "sharing": {
        "google": null,
        "facebook": null,
        "twitter": null,
        "weibo": null,
        "all": null
        }
  },
  "pdf": {
    "paperSize":"a4"
  }
}

```

**output**, with DEBUG environment variable enabled:

```
Error: Command failed: /bin/sh -c ebook-convert /tmp/tmp-3581jg6ra5c/SUMMARY.html /tmp/tmp-3581jg6ra5c/index.pdf --title="Robot 文档" --comments="Robot 的思路与实现" --authors="Microtaku" --language="zh-cn" --book-producer="GitBook" --publisher="GitBook" --chapter="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter ')]" --chapter-mark="pagebreak" --page-breaks-before="/" --level1-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-1 ')]" --level2-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-2 ')]" --level3-toc="descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' book-chapter-3 ')]" --no-chapters-in-toc --max-levels="1" --breadth-first --margin-left="62" --margin-right="62" --margin-top="56" --margin-bottom="56" --pdf-default-font-size="12" --pdf-mono-font-size="12" --paper-size="a4" --pdf-header-template="<p class='header'><span>Robot 文档</span></p>" --pdf-footer-template="<p class='footer'><span>_SECTION_</span> <span style='float:right;'>_PAGENUM_</span></p>"
 1% Converting input to HTML...
InputFormatPlugin: HTML Input running
on /tmp/tmp-3581jg6ra5c/SUMMARY.html
Building file list...
Normalizing filename cases
Rewriting HTML links
34% Running transforms on ebook...
Merging user specified metadata...
Detecting structure...
        Detected chapter: 介绍
        Detected chapter: 总体实现架构
        Detected chapter: 代码目录结构
        Detected chapter: 开发环境
        Detected chapter: 关键实现
Auto generated TOC with 5 entries.
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...

    at ChildProcess.exithandler (child_process.js:196:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:764:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

**Comment by c0ldcat** [comment]
try calibre 2.77.0
it may be caused by calibre
