### ISSUE TITLE
Lunr fails with some books

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/gitbook#941]
In the long term, search and lunr indexing should be done by a plugin (default: `gitbook-plugin-search`).

Lunr is failing for a book (not really big):

```
RangeError: Maximum call stack size exceeded
    at null.<anonymous> (/Users/samypesse/Projects/GitBook/gitbook/node_modules/lunr/lunr.js:937:34)
    at Array.forEach (native)
    at lunr.Index.add (/Users/samypesse/Projects/GitBook/gitbook/node_modules/lunr/lunr.js:933:16)
    at Book.indexPage (/Users/samypesse/Projects/GitBook/gitbook/lib/book.js:744:22)
    at wrapper [as indexPage] (/Users/samypesse/Projects/GitBook/gitbook/node_modules/lodash/index.js:3095:19)
    at /Users/samypesse/Projects/GitBook/gitbook/lib/book.js:596:14
    at _fulfilled (/Users/samypesse/Projects/GitBook/gitbook/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/samypesse/Projects/GitBook/gitbook/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/samypesse/Projects/GitBook/gitbook/node_modules/q/q.js:749:13)
    at /Users/samypesse/Projects/GitBook/gitbook/node_modules/q/q.js:557:44
```

I tried updating lunr to `0.5.12`, but it's still failing.

**Comment by AaronO** [comment]
In the long term we should probably forget about `lunr` and use `elasticsearch` in production (on `gitbook.com`) (so we would probably keep `lunr` as a fallback)

That would fix many issues:
    * Better chinese/russian/... support
    * Search across all books
    * No problem with large books

**Comment by SamyPesse** [comment]
I'm talking about search inside books built with gitbook, but not always hosted on gitbook.com (CERN, that user, ...), we have to find another solution that just dump search for these users ...

Elasticsearch is a `gitbook.com` issue, and is not related to this, since we'll just have to disable a `search` plugin for `gitbook.com` ...

**Comment by AaronO** [comment]
That bug you have right there with `lunr` should be fixed.

But we can't have a perfect client side search solution:
* We won't be able to support chinese solution, because tokenizing chinese (which you need both to query and index) takes a lot of code/data and we can't just ship a 5mb js file just to tokenize chinese.

Maybe I'm wrong, but bugs aside I think `lunr` is more or less the best we can do 100% client side.

This seems to be a bug that should be fixed in `lunr` not that we should replace `lunr`.

**Comment by SamyPesse** [comment]
I know ... but the subject of this issue is to find a solution to fix search in the next short-mid term releases, client search should always be an available feature (right now in the core, in the future as a plugin).

Server side search with Elasticsearch is another issue, that we are already talked about and agreed on; this has nothing to do here !
