### ISSUE TITLE
build pdf error, but website can be build and gitbook.com can generate pdf.

### ISSUE THREAD

**Issue by jarronshih** [GitbookIO/gitbook#984]
not sure where is wrong.

```bash
$ gitbook pdf . --debug
info: loading book configuration....OK 
info: load plugin gitbook-plugin-contractbridge ....OK 
info: load plugin gitbook-plugin-disqus ....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: >> 3 plugins loaded 
info: start generation with pdf generator 
info: clean pdf generatorOK 
info: write SUMMARY.html 

TypeError: arg.replace is not a function
TypeError: arg.replace is not a function
    at escapeShellArg (/Users/jarronsh/.gitbook/versions/2.4.3/lib/utils/string.js:6:15)
    at /Users/jarronsh/.gitbook/versions/2.4.3/lib/utils/string.js:16:24
    at /Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:2275:27
    at /Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:2046:14)
    at /Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:3043:18
    at baseMap (/Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:2274:7)
    at map (/Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:6710:14)
    at interceptor (/Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:12240:26)
    at Function.thru (/Users/jarronsh/.gitbook/versions/2.4.3/node_modules/lodash/index.js:5927:26)
```

**Comment by SamyPesse** [comment]
What is your `book.json` ?

**Comment by jarronshih** [comment]
I find out the reason, I use author in book.json #649. close.

**Comment by SamyPesse** [comment]
It should not fail with this error, can you paste here (if public) or send me the book.json at samy@gitbook.com (if private)

**Comment by jarronshih** [comment]
https://github.com/jarronshih/gitbook-btu-bws/tree/c36a5104c1b333fb81ebc58d5b10c90697cac5e4

{
    "name": "gitbook-btu-bws",
    "title": "BTU-BWS",
    "description": "The book is about the nature 5533 system used by BTU.",
    "language": "zh",
    "plugins": ["contractbridge", "disqus"],
    "pluginsConfig": {
        "disqus": {
            "shortName": "gitbook-btu-bws"
        }
    },
    "githubId": "jarronshih/gitbook-btu-bws",
    "author": ["Jarron Shih", "BTUers"]
}
