### ISSUE TITLE
Gitbook PDF generation failed

### ISSUE THREAD

**Issue by juanghurtado** [GitbookIO/gitbook#998]
Hi there!

I'm having an error while trying to generate a PDF version of my book with Gitbook 2.5.1, but everything is ok with Gitbook 2.3.1.

You can find a failing example in https://github.com/inyenia/gitbook-template/tree/master/doc

The error is:

```
~/Desktop/gitbook-template/doc master 7c5d136 dirty
❯ gitbook pdf --debug
info: loading book configuration....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-search ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: >> 4 plugins loaded
info: Parsing multilingual book, with 1 languages
info: Preparing language book es
info: loading book configuration....OK
info: load plugin gitbook-plugin-highlight ....OK
info: load plugin gitbook-plugin-search ....OK
info: load plugin gitbook-plugin-sharing ....OK
info: load plugin gitbook-plugin-fontsettings ....OK
info: >> 4 plugins loaded
info: start generation with pdf generator
info: clean pdf generatorOK
info: start generation with pdf generator
info: clean pdf generatorOK
info: write SUMMARY.html

TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at getPseudoElementType (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/juice/lib/juice.js:266:15)
    at handleRule (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/juice/lib/juice.js:104:29)
    at Array.forEach (native)
    at inlineDocument (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/juice/lib/juice.js:84:9)
    at juiceDocument (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/juice/lib/juice.js:296:3)
    at juice (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/juice/lib/juice.js:25:13)
    at Generator.getPDFTemplate (/Users/juanghurtado/.gitbook/versions/2.5.1/lib/generators/ebook.js:69:11)
    at wrapper [as getPDFTemplate] (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/lodash/index.js:3095:19)
    at /Users/juanghurtado/.gitbook/versions/2.5.1/lib/generators/ebook.js:125:47
    at _fulfilled (/Users/juanghurtado/.gitbook/versions/2.5.1/node_modules/q/q.js:787:54)
```

Thanks!

**Comment by onevcat** [comment]
Same error for me after upgrading to 2.5.1.

**Comment by SamyPesse** [comment]
Fixed by https://github.com/GitbookIO/gitbook/commit/a7f49015c1af7e2b707d321bdcaa72579190f6ac

I'll release 2.5.2 today.

**Comment by onevcat** [comment]
It was fixed. Thanks for it!
